### ISSUE TITLE
Error trying to execute: ssd1306_stats.py

### ISSUE THREAD

**Issue by roadglide03** [UCTRONICS/U6143_ssd1306#2]
okay I installed raspberry os on another card and tried getting this to work but getting the following error.  I did enable the interface option.

```
> andy@raspberrypi:~/git/U6143_ssd1306-master $ sudo python3 ssd1306_stats.py
> Traceback (most recent call last):
>   File "ssd1306_stats.py", line 18, in <module>
>     i2c = busio.I2C(SCL, SDA)
>   File "/usr/local/lib/python3.7/dist-packages/busio.py", line 31, in __init__
>     self.init(scl, sda, frequency)
>   File "/usr/local/lib/python3.7/dist-packages/busio.py", line 72, in init
>     (scl, sda), i2cPorts
> ValueError: No Hardware I2C on (scl,sda)=(3, 2)
> Valid I2C ports: ((1, 3, 2), (0, 1, 0))
> andy@raspberrypi:~/git/U6143_ssd1306-master $ 
> 
```

**Comment by roadglide03** [comment]
After reboot worked fine, sorry about that
